# SPDX-FileCopyrightText: © 2026 Tyler Nivin
# SPDX-License-Identifier: MIT

# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: v1.10.1
_src_path: gh:nivintw/copier-everything
author_email: tyler@nivin.tech
author_name: Tyler Nivin
contains_ansible: false
contains_python: false
include_devcontainer: false
include_docker: false
include_docs_site: true
include_helm: false
include_sql: false
include_terraform: false
initialize_repository: false
license: MIT
markdown_has_frontmatter: true
project_description: Tyler Nivin's Claude Code plugin marketplace.
project_name: nivintw-claude-skills
project_slug: nivintw-claude-skills
repo_name: nivintw-claude-skills
repo_owner: nivintw
test_frameworks:
- bats
year: 2026
