# SPDX-FileCopyrightText: © 2026 Tyler Nivin
# SPDX-License-Identifier: MIT

version = 1

# Files that can't carry an SPDX header (no comment syntax / generated). Everything
# else gets a real header from hawkeye (see licenserc.toml).
# Markdown is included here (not headered inline by hawkeye) because this project has
# frontmatter-first markdown where a line-1 SPDX comment would break the YAML.
[[annotations]]
path = ["**/*.json", "**/.vscode/*", "**/*.md"]
SPDX-FileCopyrightText = "© 2026 Tyler Nivin"
SPDX-License-Identifier = "MIT"
